services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    env_file:
      - ./.env
    container_name: postgresdb-customer
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - '6432:6432'
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      - postgres
    build:
      context: ./.
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - "4040:4040"
    environment:
      - SPRING_CUSTOMER_DATASOURCE_URL=jdbc:postgresql://postgresdb:6432/$POSTGRESDB_DATABASE
      - SPRING_CUSTOMER_DATASOURCE_USERNAME=$POSTGRESDB_USER
      - SPRING_CUSTOMER_DATASOURCE_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - SPRING_CUSTOMER_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  db:
